language: node_js
node_js:
  - "5.4"
before_install:
  - npm install -g bower
  - npm install -g phantomjs
  - npm install -g casperjs
script:
  - bower install
  - sleep 5s
  - cd test
  - casperjs test markette-test.js